### ISSUE TITLE
Embedding Depth Sensor

### ISSUE THREAD

**Issue by shlomi-amitai** [MIT-SPARK/Kimera#12]
Hi Guys,

How would you recommend embedding a depth sensor into your architecture?

**Comment by ToniRV** [comment]
We can already use a depth sensor for mapping in Kimera-Semantics.
If your depth sensor can stream data through ROS, it should be a matter of changing topic names in Kimera-Semantics.
Otherwise, you may need to interface the depth sensor directly with Kimera-Semantics or to ROS.
