### ISSUE TITLE
Using Kimera on mobile platform

### ISSUE THREAD

**Issue by TheBricktop** [MIT-SPARK/Kimera#13]
Is there a way to use kimera on nvidia jetson nano for example? Would performance be acceptable for realtime uses like VR or drone navigation ?

**Comment by ToniRV** [comment]
Yes, we have used Kimera on an Nvidia Jetson TX2: more details in our paper https://arxiv.org/abs/2101.06894

**Comment by ToniRV** [comment]
See also #13 and https://github.com/MIT-SPARK/Kimera-VIO/issues/154
