### ISSUE TITLE
where is the code?

### ISSUE THREAD

**Issue by Asiyeh-Bahaloo** [MIT-SPARK/Kimera#16]
where is the source code of the project? or the library to download?

**Comment by WentingXu3o3** [comment]
Same question

**Comment by DreamWaterFound** [comment]
[Kimera-VIO & Kimera-Mesher](https://github.com/MIT-SPARK/Kimera-VIO)
[Kimera-RPGO](https://github.com/MIT-SPARK/Kimera-RPGO)
[Kimera-Semantics](https://github.com/MIT-SPARK/Kimera-Semantics)

These links are mentioned in the Readme of the current repository. I hope it can be helpful to you.
