### ISSUE TITLE
Kimera with Iphone sensor

### ISSUE THREAD

**Issue by hyeonmin11** [MIT-SPARK/Kimera#17]
HI, I have a question about the sensor which can use with Kimera.
Can I use Kimera with Iphone sensor?
Thanks.

**Comment by lucacarlone** [comment]
Hi! 

Kimera supports stereo, mono, and RGB-D cameras (and it also requires an IMU to run). 
You should be able to use a phone camera as long as you have a good calibration of the camera intrinsic and camera-imu extrinsics and can access the camera and IMU streams. Depending on the iPhone model, you should also be able to leverage depth, hence falling back to an RGB-D setup. As far as I know, Apple already has APIs to provide visual-inertial odometry estimates via ARKit (https://developer.apple.com/augmented-reality/arkit/), but you might not be able to control/inspect the details of their pipeline. 

I hope this helps!

**Comment by lucacarlone** [comment]
I'm going to close this issue for now. Feel free to reopen it if you have further questions.
Note that in general we might not be able to provide support to run Kimera on your own application.
