### ISSUE TITLE
Reconstruction comparison with ElasticFusion and InfiniTAM

### ISSUE THREAD

**Issue by therishidesai** [MIT-SPARK/Kimera#6]
Have you guys done reconstruction comparisons with ElasticFusion and InfiniTAM. There was a tool called SurfReg that the ICL-NUIM dataset creators made to allow you measure the quality of a reconstruction.

**Comment by ToniRV** [comment]
Hi @apache8080,

Tbh, I have never managed to get ElasticFusion or InfiniTAM working :sweat: 

We actually use ground-truth 3D meshes when evaluating a run in simulation, and pointclouds for the Euroc dataset.
We don't have a way to evaluate the quality of unmapped scenes though, but I guess there is not much you can say about it beyond some qualitative inspection.

**Comment by apache8080** [comment]
I feel your pain.

Our lab has been able to get ElasticFusion running but InfiniTAM hasn’t been the easiest thing to setup. I got it running eventually but we are still running into quality issues. Right now we are trying to recreate the results from the InfiniTAM paper where they compare reconstruction quality with ElasticFusion.

If you guys have a way of exporting the reconstruction as a PLY or STL file then I could also try adding Kimera to our comparisons.

**Comment by apache8080** [comment]
I guess one challenge is the SurfReg tool seems to only work well with the ICL-NUIM dataset and that dataset doesn’t contain an IMU.

**Comment by ToniRV** [comment]
@apache8080 sorry I just read your last comments.
It is very easy to get the PLY: just call at the end of the run:
```
rosservice call /kimera_semantics_node/generate_mesh
```
I would be very interested to know your results! Thanks!

**Comment by Viky397** [comment]
I've got my data running on ElasticFusion which doesn't look amazing...(have been trying to get Kintinuous up and running to no avail...)
Just discovered Kimera and am excited to give it a shot with my RGBD data!
