### ISSUE TITLE
What environment do you use?

### ISSUE THREAD

**Issue by GuoChuan1314** [MIT-SPARK/Kimera#9]
Which version of Ubuntu do you implement? The 20.04 I used now reports a lot of errors.

**Comment by ToniRV** [comment]
We have extensively tested with 16.04/18.04
Nevertheless, I think there is a branch for Kimera-VIO that works for 20.04: https://github.com/MIT-SPARK/Kimera-VIO/issues/60

**Comment by amirhossein-hassankhani** [comment]
What is the hardware requirement for using Kimera without any problem (no lag, ...)?

**Comment by ToniRV** [comment]
See #13 and https://github.com/MIT-SPARK/Kimera-VIO/issues/154
